Repository Siv3D/OpenSiv3D, pull requests merged in 2022-11, with the labels that each got.

#909 OrderedTable 型を追加
  Siv3D/include/Siv3D.hpp
  Siv3D/include/Siv3D/OrderedTable.hpp
  Siv3D/include/Siv3D/detail/OrderedTable.ipp
  Siv3D/include/ThirdParty/parallel_hashmap/btree.h
  WindowsDesktop/Siv3D.vcxproj
  WindowsDesktop/Siv3D.vcxproj.filters
Labels: proposal, v0.6.6

#922 OSC 通信機能 (#919)
  Linux/CMakeLists.txt
  Siv3D/include/Siv3D.hpp
  Siv3D/include/Siv3D/OSCArgument.hpp
  Siv3D/include/Siv3D/OSCMessage.hpp
  Siv3D/include/Siv3D/OSCReceiver.hpp
  Siv3D/include/Siv3D/OSCSender.hpp
  Siv3D/include/Siv3D/OSCTypeTag.hpp
  Siv3D/include/Siv3D/ReceivedOSCMessage.hpp
  Siv3D/include/Siv3D/detail/OSCArgument.ipp
  Siv3D/src/Siv3D/Input/SivInput.cpp
  Siv3D/src/Siv3D/LicenseManager/LicenseList.hpp
  Siv3D/src/Siv3D/OSCMessage/OSCMessageDetail.cpp
  Siv3D/src/Siv3D/OSCMessage/OSCMessageDetail.hpp
  Siv3D/src/Siv3D/OSCMessage/SivOSCMessage.cpp
  Siv3D/src/Siv3D/OSCReceiver/OSCPacketListener.cpp
  Siv3D/src/Siv3D/OSCReceiver/OSCPacketListener.hpp
  Siv3D/src/Siv3D/OSCReceiver/OSCReceiverDetail.cpp
  Siv3D/src/Siv3D/OSCReceiver/OSCReceiverDetail.hpp
  Siv3D/src/Siv3D/OSCReceiver/SivOSCReceiver.cpp
  Siv3D/src/Siv3D/OSCSender/SivOSCSender.cpp
  Siv3D/src/ThirdParty/oscpack/ip/IpEndpointName.cpp
  Siv3D/src/ThirdParty/oscpack/ip/IpEndpointName.h
  Siv3D/src/ThirdParty/oscpack/ip/NetworkingUtils.h
  Siv3D/src/ThirdParty/oscpack/ip/PacketListener.h
  Siv3D/src/ThirdParty/oscpack/ip/TimerListener.h
  Siv3D/src/ThirdParty/oscpack/ip/UdpSocket.h
  Siv3D/src/ThirdParty/oscpack/ip/posix/NetworkingUtils.cpp
  Siv3D/src/ThirdParty/oscpack/ip/posix/UdpSocket.cpp
  Siv3D/src/ThirdParty/oscpack/ip/win32/NetworkingUtils.cpp
  Siv3D/src/ThirdParty/oscpack/ip/win32/UdpSocket.cpp
  Siv3D/src/ThirdParty/oscpack/osc/MessageMappingOscPacketListener.h
  Siv3D/src/ThirdParty/oscpack/osc/OscException.h
  Siv3D/src/ThirdParty/oscpack/osc/OscHostEndianness.h
  Siv3D/src/ThirdParty/oscpack/osc/OscOutboundPacketStream.cpp
  Siv3D/src/ThirdParty/oscpack/osc/OscOutboundPacketStream.h
  Siv3D/src/ThirdParty/oscpack/osc/OscPacketListener.h
  Siv3D/src/ThirdParty/oscpack/osc/OscPrintReceivedElements.cpp
  Siv3D/src/ThirdParty/oscpack/osc/OscPrintReceivedElements.h
  Siv3D/src/ThirdParty/oscpack/osc/OscReceivedElements.cpp
  Siv3D/src/ThirdParty/oscpack/osc/OscReceivedElements.h
  Siv3D/src/ThirdParty/oscpack/osc/OscTypes.cpp
  Siv3D/src/ThirdParty/oscpack/osc/OscTypes.h
  ThirdParty.md
  WindowsDesktop/Siv3D.vcxproj
  WindowsDesktop/Siv3D.vcxproj.filters
  macOS/OpenSiv3D.xcodeproj/project.pbxproj
Labels: v0.6.7

#923 Serializationのマクロを修正
  Siv3D/include/Siv3D/Serialization.hpp
Labels: Type: Bug, v0.6.7
