Repository Siv3D/OpenSiv3D, pull requests merged in 2022-06, with the labels that each got.

#811 Array.hppの誤字修正
  Siv3D/include/Siv3D/Array.hpp
Labels: v0.6.5

#821 BigInt/BigFloat の比較演算子のバグを修正
  Siv3D/include/Siv3D/BigFloat.hpp
  Siv3D/include/Siv3D/BigInt.hpp
Labels: Type: Bug, v0.6.5

#822 算術型から BigInt/BigFloat を引くときの無駄なコピーを回避
  Siv3D/include/Siv3D/BigFloat.hpp
  Siv3D/include/Siv3D/BigInt.hpp
Labels: Type: Performance, v0.6.5
