Repository Siv3D/OpenSiv3D, pull requests merged in 2023-09, with the labels that each got.

#1088 #1084 の修正
  Siv3D/include/Siv3D/detail/RandomColor.ipp
Labels: Type: Bug, v0.6.12

#1085 typo を修正しました。
  Siv3D/src/Siv3D-Platform/WindowsDesktop/Siv3D/Renderer/D3D11/Device/D3D11Adapter.hpp
  Siv3D/src/Siv3D-Platform/WindowsDesktop/Siv3D/Renderer/D3D11/Device/D3D11Device.cpp
  Siv3D/src/Siv3D-Platform/WindowsDesktop/Siv3D/Renderer/D3D11/Device/D3D11Device.hpp
  Siv3D/src/Siv3D-Platform/WindowsDesktop/Siv3D/Renderer/D3D11/Device/D3D11DeviceHelper.cpp
  Siv3D/src/Siv3D-Platform/WindowsDesktop/Siv3D/Renderer/D3D11/Device/D3D11DeviceHelper.hpp
  Siv3D/src/Siv3D-Platform/WindowsDesktop/Siv3D/Renderer/D3D11/Device/D3D11DeviceInfo.hpp
  Siv3D/src/Siv3D-Platform/WindowsDesktop/Siv3D/Renderer/D3D11/SwapChain/D3D11SwapChain.cpp
Labels: v0.6.12

#1090 Image::rotate90(int32 n),rotated90(int32 n),の追加
  Siv3D/include/Siv3D/Image.hpp
  Siv3D/src/Siv3D/Image/SivImage.cpp
Labels: v0.6.12

#1092 CONTRIBUTING.ja.md を改善
  CONTRIBUTING.ja.md
Labels: Type: Documentation

#1081 SceneManagerのinit関数に最初のフェードイン・フェードアウトを指定できる機能を追加
  Siv3D/include/Siv3D/SceneManager.hpp
  Siv3D/include/Siv3D/detail/SceneManager.ipp
Labels: Type: Enhancement, v0.6.12

#1107 [共通] IME 改修 / SimpleGUI::IMECandidateWindow()
  Siv3D/include/Siv3D/SimpleGUI.hpp
  Siv3D/include/Siv3D/TextInput.hpp
  Siv3D/src/Siv3D-Platform/WindowsDesktop/Siv3D/TextInput/CTextInput.cpp
  Siv3D/src/Siv3D-Platform/WindowsDesktop/Siv3D/TextInput/CTextInput.hpp
  Siv3D/src/Siv3D-Platform/WindowsDesktop/Siv3D/TextInput/WindowsIME.cpp
  Siv3D/src/Siv3D-Platform/WindowsDesktop/Siv3D/TextInput/WindowsIME.hpp
  Siv3D/src/Siv3D/SimpleGUI/SivSimpleGUI.cpp
  Siv3D/src/Siv3D/TextInput/ITextInput.hpp
  Siv3D/src/Siv3D/TextInput/SivTextInput.cpp
Labels: v0.6.12

#1108 Image::clipped() の性能を改善
  Siv3D/include/Siv3D/Image.hpp
  Siv3D/src/Siv3D/Image/SivImage.cpp
  Siv3D/src/Siv3D/Script/Bind/ScriptImage.cpp
Labels: Type: Performance, v0.6.12

#1102 Vector2D,Pointにrotate90(int32)系を追加 #1093
  Siv3D/include/Siv3D/Point.hpp
  Siv3D/include/Siv3D/Vector2D.hpp
  Siv3D/include/Siv3D/detail/Point.ipp
  Siv3D/include/Siv3D/detail/Vector2D.ipp
Labels: v0.6.12
