Repository Siv3D/OpenSiv3D, pull requests merged in 2023-08, with the labels that each got.

#1026 Font でタブの進みが 0 になるバグを修正
  Siv3D/src/Siv3D/Font/GlyphCache/GlyphCacheCommon.cpp
Labels: v0.6.11

#1035 [共通] トラブルシューティング機能 #1007
  Linux/CMakeLists.txt
  Siv3D/src/Siv3D-Platform/WindowsDesktop/Siv3D/FreestandingMessageBox/FreestandingMessageBox_Windows.cpp
  Siv3D/src/Siv3D-Platform/macOS/Siv3D/FreestandingMessageBox/FreestandingMessageBox_macOS.cpp
  Siv3D/src/Siv3D/AssetMonitor/CAssetMonitor.cpp
  Siv3D/src/Siv3D/Audio/SivAudio.cpp
  Siv3D/src/Siv3D/DynamicMesh/SivDynamicMesh.cpp
  Siv3D/src/Siv3D/Effect/SivEffect.cpp
  Siv3D/src/Siv3D/Font/SivFont.cpp
  Siv3D/src/Siv3D/FreestandingMessageBox/FreestandingMessageBox.hpp
  Siv3D/src/Siv3D/Mesh/SivMesh.cpp
  Siv3D/src/Siv3D/Model/SivModel.cpp
  Siv3D/src/Siv3D/PixelShader/SivPixelShader.cpp
  Siv3D/src/Siv3D/Script/SivScript.cpp
  Siv3D/src/Siv3D/Texture/SivTexture.cpp
  Siv3D/src/Siv3D/Troubleshooting/Troubleshooting.cpp
  Siv3D/src/Siv3D/Troubleshooting/Troubleshooting.hpp
  Siv3D/src/Siv3D/VertexShader/SivVertexShader.cpp
  Web/CMakeLists.txt
  WindowsDesktop/Siv3D.vcxproj
  WindowsDesktop/Siv3D.vcxproj.filters
  macOS/OpenSiv3D.xcodeproj/project.pbxproj
Labels: v0.6.11

#1043 [共通] 軌跡描画
  Linux/CMakeLists.txt
  Siv3D/include/Siv3D.hpp
  Siv3D/include/Siv3D/Trail.hpp
  Siv3D/include/Siv3D/TrailMotion.hpp
  Siv3D/src/Siv3D/Common/Siv3DEngine.cpp
  Siv3D/src/Siv3D/Common/Siv3DEngine.hpp
  Siv3D/src/Siv3D/Trail/SivTrail.cpp
  Siv3D/src/Siv3D/TrailMotion/SivTrailMotion.cpp
  Siv3D/src/Siv3D/TrailRenderer/CTrailRenderer.cpp
  Siv3D/src/Siv3D/TrailRenderer/CTrailRenderer.hpp
  Siv3D/src/Siv3D/TrailRenderer/ITrailRenderer.hpp
  Siv3D/src/Siv3D/TrailRenderer/TrailRendererFactory.cpp
  Web/CMakeLists.txt
  WindowsDesktop/Siv3D.vcxproj
  WindowsDesktop/Siv3D.vcxproj.filters
  macOS/OpenSiv3D.xcodeproj/project.pbxproj
Labels: v0.6.11

#1049 SimpleFollowCamera3D
  Linux/CMakeLists.txt
  Siv3D/include/Siv3D.hpp
  Siv3D/include/Siv3D/SimpleFollowCamera3D.hpp
  Siv3D/src/Siv3D/SimpleFollowCamera3D/SivSimpleFollowCamera3D.cpp
  Web/CMakeLists.txt
  WindowsDesktop/Siv3D.vcxproj
  WindowsDesktop/Siv3D.vcxproj.filters
  macOS/OpenSiv3D.xcodeproj/project.pbxproj
Labels: v0.6.11

#1054 (JSON.hpp) operator bool() の説明が逆になってるのを修正
  Siv3D/include/Siv3D/JSON.hpp
Labels: Type: Documentation, v0.6.12

#1058 Pointクラスに剰余演算子「%」と「%=」を追加
  Siv3D/include/Siv3D/Point.hpp
  Siv3D/include/Siv3D/detail/Point.ipp
Labels: v0.6.12

#1064 コピーが重いクラスに右辺値向けオーバーロードを追加
  Siv3D/include/Siv3D/Array.hpp
  Siv3D/include/Siv3D/Image.hpp
  Siv3D/include/Siv3D/LineString.hpp
  Siv3D/include/Siv3D/MultiPolygon.hpp
  Siv3D/include/Siv3D/Polygon.hpp
  Siv3D/include/Siv3D/String.hpp
  Siv3D/include/Siv3D/Wave.hpp
  Siv3D/include/Siv3D/detail/Array.ipp
  Siv3D/include/Siv3D/detail/BoolArray.ipp
  Siv3D/src/Siv3D/Image/SivImage.cpp
  Siv3D/src/Siv3D/LineString/SivLineString.cpp
  Siv3D/src/Siv3D/MultiPolygon/SivMultiPolygon.cpp
  Siv3D/src/Siv3D/Polygon/SivPolygon.cpp
  Siv3D/src/Siv3D/Script/Bind/ScriptImage.cpp
  Siv3D/src/Siv3D/Script/Bind/ScriptLineString.cpp
  Siv3D/src/Siv3D/Script/Bind/ScriptPolygon.cpp
  Siv3D/src/Siv3D/String/SivString.cpp
  Siv3D/src/Siv3D/Wave/SivWave.cpp
Labels: Type: Performance, v0.6.12

#1070 Rect, RectF から角度を指定して平行四辺形を作る関数
  Siv3D/include/Siv3D/Rect.hpp
  Siv3D/include/Siv3D/RectF.hpp
  Siv3D/include/Siv3D/detail/Rect.ipp
  Siv3D/include/Siv3D/detail/RectF.ipp
Labels: v0.6.12

#1071 戻り値の型が const な値になっているメンバ関数を修正
  Siv3D/include/Siv3D/SceneManager.hpp
  Siv3D/include/Siv3D/Shape2D.hpp
  Siv3D/include/Siv3D/detail/SceneManager.ipp
  Siv3D/include/Siv3D/detail/Shape2D.ipp
Labels: v0.6.12

#1074 Point3D
  Linux/CMakeLists.txt
  Siv3D/include/Siv3D/2DShapesFwd.hpp
  Siv3D/include/Siv3D/Point3D.hpp
  Siv3D/include/Siv3D/PointVector.hpp
  Siv3D/include/Siv3D/Vector3D.hpp
  Siv3D/include/Siv3D/detail/Point.ipp
  Siv3D/include/Siv3D/detail/Point3D.ipp
  Siv3D/include/Siv3D/detail/Serialization.ipp
  Siv3D/include/Siv3D/detail/Vector3D.ipp
  Siv3D/src/Siv3D/Point/SivPoint.cpp
  Siv3D/src/Siv3D/Point3D/SivPoint3D.cpp
  Web/CMakeLists.txt
  WindowsDesktop/Siv3D.vcxproj
  WindowsDesktop/Siv3D.vcxproj.filters
  macOS/OpenSiv3D.xcodeproj/project.pbxproj
Labels: v0.6.12
