Repository Siv3D/OpenSiv3D, pull requests merged in 2024-02, with the labels that each got.

#1198 Circle::drawArc(LineStyle::RoundCap) で両端がグラデーションしない問題を修正
  Siv3D/src/Siv3D/Renderer2D/Vertex2DBuilder.cpp
  Siv3D/src/Siv3D/Renderer2D/Vertex2DBuilder.hpp
Labels: Type: Bug, v0.6.14

#1200 example shadow
  Linux/App/example/shader/glsl/default3d_forward_shadow_depth.frag
  Linux/App/example/shader/glsl/default3d_forward_shadow_shading.frag
  Linux/App/example/shader/hlsl/default3d_forward_shadow.hlsl
  Siv3D/include/Siv3D/Mat4x4.hpp
  Siv3D/include/Siv3D/detail/Mat4x4.ipp
  WindowsDesktop/App/example/shader/glsl/default3d_forward_shadow_depth.frag
  WindowsDesktop/App/example/shader/glsl/default3d_forward_shadow_shading.frag
  WindowsDesktop/App/example/shader/hlsl/default3d_forward_shadow.hlsl
  macOS/App/example/shader/glsl/default3d_forward_shadow_depth.frag
  macOS/App/example/shader/glsl/default3d_forward_shadow_shading.frag
  macOS/App/example/shader/hlsl/default3d_forward_shadow.hlsl
Labels: v0.6.14

#1206 Circularにlerp関数を追加
  Siv3D/include/Siv3D/Circular.hpp
  Siv3D/include/Siv3D/detail/Circular.ipp
Labels: v0.6.15

#1207 BMPDecoder の全ビット深度対応と、それにあたっての修正
  Siv3D/src/Siv3D/ImageFormat/BMP/BMPDecoder.cpp
Labels: v0.6.15
